name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Grant execute permission for gradlew
      run: chmod +x ./web/gradlew
    - name: Build Project
      run: cd web && ./gradlew build
