name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Grant execute permission for gradlew
      run: chmod +x ./web/gradlew
    - name: Build Project
      run: ./web/gradlew build
    - name: Copy files to Server
      env:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SHH_USER }}
        port: ${{ secrets.SHH_PORT }}
        key: ${{ secrets.SHH_KEY }}
        source: "web/build/libs/*.jar"
        target: "~/docker/btorres.dev"
      run:
        echo key > ${key}
        scp ${source} -i ./key ${username}@${host}:${target} 
  
