name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build Project
      run: ./web/gradlew build
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file web/Dockerfile --build-arg JAR_FILE=build/libs/\*.jar -t btorres.dev
